name: mini_cage_snakeoil
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.1=h81ee809_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=h6cefb37_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - gymnasium==0.29.1
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - sentry-sdk==2.34.1
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.3.2
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.7.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.0
      - werkzeug==3.1.3
